//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::admin::Entity as Admin;
pub use super::comment::Entity as Comment;
pub use super::post::Entity as Post;
pub use super::tag::Entity as Tag;
